First Task created.
zanasobhani/java-script-practice pull request #1
Opened 2024-03-19 11:52 UTC by zanasobhani

2024-04-03 09:46 UTC, maks-io requested changes
Sieht schon ganz gut aus, allerdings sind 2 Übungen noch nicht korrekt - beachte meine einzelnen Kommentare für mehr Details

2024-04-03 09:46 UTC, maks-io commented on ÜbungenzuVerzweigungen/5.js
> +            break;
Wenn ich eine Zahl eingebe bekomme ich auch "Konsonant"

2024-04-03 09:46 UTC, maks-io commented on ÜbungenzuVerzweigungen/5.js
> +            break;
Bitte benutze Fall-Through Logik, damit der Code kürzer wird.

2024-04-03 09:46 UTC, maks-io commented on ÜbungenzuVerzweigungen/8.js
> +}
Wenn ich eine Zahl wie etwa `6.7` eingebe bekomme ich "The number is even" und nicht "The number is decimal"

2024-04-03 20:03 UTC, zanasobhani commented
Thank you for your attention.I have corrected errors.

2024-04-08 07:59 UTC, maks-io approved these changes
Sehr gut. Übrigens: solange du nicht asynchron auf etwas warten musst (z.B. auf einen user input), musst du keine execute function verwenden

2024-04-08 08:34 UTC, merged